### ISSUE TITLE
wine: failed to open "allredist/redist/2010/vcredist_x64.exe": c0000135

### ISSUE THREAD

**Issue by LastEmperor0** [LinSoftWin/Photoshop-CC2022-Linux#108]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
CC2021

**Describe the bug**
wine: failed to open "allredist/redist/2010/vcredist_x64.exe": c0000135
wine: failed to open "allredist/redist/2010/vcredist_x86.exe": c0000135
wine: failed to open "allredist/redist/2012/vcredist_x86.exe": c0000135
wine: failed to open "allredist/redist/2012/vcredist_x64.exe": c0000135
wine: failed to open "allredist/redist/2013/vcredist_x86.exe": c0000135
wine: failed to open "allredist/redist/2013/vcredist_x64.exe": c0000135
wine: failed to open "allredist/redist/2019/VC_redist.x64.exe": c0000135
wine: failed to open "allredist/redist/2019/VC_redist.x86.exe": c0000135
mkdir: cannot create directory ‘/home/alperen/PhotoshopCC2021/Adobe-Photoshop/drive_c/Program Files/Adobe’: File exists
mv: cannot stat 'allredist/photoshop.png': No such file or directory

**To Reproduce**
1: Start script by using sh photoshopcc2021.sh /home/username/
2: See the error

**System informations**
- Distro : Arch linux
- GPU : NVIDIA
- WINE version : 8.8-1

**Comment by Whax** [comment]
The problem comes from the line 16 :

https://github.com/LinSoftWin/Photoshop-CC2022-Linux/blob/b43b0c62cb042de38f7bfc3524a115a2ad96af1c/scripts/photoshop2021install.sh#L16 when the script tries to download the Google Drive File

Host yourself the `allredist.tar.xz`, edit the script consequently and all will be fine ;)

**Comment by LastEmperor0** [comment]
Oh thx

**Comment by MiMillieuh** [comment]
It should be fixed, I've hosted them like the binaries.
