### ISSUE TITLE
wine error "adobe photoshop requieres windows 10 anniversary update"

### ISSUE THREAD

**Issue by lucasterly-dev** [LinSoftWin/Photoshop-CC2022-Linux#112]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
 CC2022

**Describe the bug**
when i try to open photoshop it open a window saying: "adobe photoshop requieres windows 10 anniversary update"

**To Reproduce**
1 open photoshop 

**Expected behavior**
i dont know

**Screenshots**
(https://imgur.com/oenhcaV)

**System informations**
- Distro : Manajaro
- GPU : Intel 
- WINE version : wine-8.11

**Additional context**
help me

**Is some information are missing it might take longer to find the issue so please complete carefully**

**Comment by MiMillieuh** [comment]
The answer to your issue is in the readme... 

https://github.com/LinSoftWin/Photoshop-CC2022-Linux#requirements

https://github.com/MiMillieuh/Photoshop-CC2022-Linux/issues/94#issuecomment-1426776219
