### ISSUE TITLE
Need assistance installing it, please.

### ISSUE THREAD

**Issue by ikim23code** [LinSoftWin/Photoshop-CC2022-Linux#114]
Hello,

I just recently bought a new laptop, Lenovo Ideapad 5 PRO with AMD 7840HS CPU and integrated graphics.
I have installed Debian KDE Plasma and I have kernel 6..1.0-11-amd64 (64-bit).

When trying to install it I'm encountering the following errors in the log:

 sudo ./photoshop2021install.sh
--2023-08-18 13:17:18--  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 795034 (776K) [text/plain]
Saving to: ‘winetricks’

winetricks                                           100%[===================================================================================================================>] 776.40K  --.-KB/s    in 0.1s    

2023-08-18 13:17:19 (5.91 MB/s) - ‘winetricks’ saved [795034/795034]

0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
wine: configuration in L"/Adobe-Photoshop" has been updated.
------------------------------------------------------
warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
grep: /Adobe-Photoshop/*.reg: No such file or directory
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 28
drwxr-xr-x  7 root root 4096 Aug 18 13:17 .
drwxr-xr-x  4 root root 4096 Aug 18 13:17 ..
drwxr-xr-x  3 root root 4096 Aug 18 13:17 ProgramData
drwxr-xr-x  6 root root 4096 Aug 18 13:17 Program Files
drwxr-xr-x  6 root root 4096 Aug 18 13:17 Program Files (x86)
drwxr-xr-x  4 root root 4096 Aug 18 13:17 users
drwxr-xr-x 18 root root 4096 Aug 18 13:17 windows

Registry info:
/Adobe-Photoshop/*.reg:
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78.2M  100 78.2M    0     0  39.3M      0  0:00:01  0:00:01 --:--:-- 39.3M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1029M  100 1029M    0     0  61.0M      0  0:00:16  0:00:16 --:--:-- 69.8M
------------------------------------------------------
warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 28
drwxr-xr-x  7 root root 4096 Aug 18 13:17 .
drwxr-xr-x  4 root root 4096 Aug 18 13:17 ..
drwxr-xr-x  3 root root 4096 Aug 18 13:17 ProgramData
drwxr-xr-x  6 root root 4096 Aug 18 13:17 Program Files
drwxr-xr-x  6 root root 4096 Aug 18 13:17 Program Files (x86)
drwxr-xr-x  4 root root 4096 Aug 18 13:17 users
drwxr-xr-x 18 root root 4096 Aug 18 13:17 windows

Registry info:
/Adobe-Photoshop/system.reg:#arch=win64
/Adobe-Photoshop/user.reg:#arch=win64
/Adobe-Photoshop/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
019c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
019c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01a4:err:mscoree:LoadLibraryShim error reading registry key for installroot
01a4:err:mscoree:LoadLibraryShim error reading registry key for installroot
01a4:err:mscoree:LoadLibraryShim error reading registry key for installroot
01a4:err:mscoree:LoadLibraryShim error reading registry key for installroot
01c8:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01c8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01d0:err:mscoree:LoadLibraryShim error reading registry key for installroot
01d0:err:mscoree:LoadLibraryShim error reading registry key for installroot
01d0:err:mscoree:LoadLibraryShim error reading registry key for installroot
01d0:err:mscoree:LoadLibraryShim error reading registry key for installroot
0204:err:richedit:ReadStyleSheet skipping optional destination
0204:err:richedit:ReadStyleSheet skipping optional destination
0204:err:richedit:ReadStyleSheet skipping optional destination
0204:err:richedit:ReadStyleSheet skipping optional destination
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
01dc:err:mscoree:LoadLibraryShim error reading registry key for installroot
023c:err:richedit:ReadStyleSheet skipping optional destination
023c:err:richedit:ReadStyleSheet skipping optional destination
023c:err:richedit:ReadStyleSheet skipping optional destination
023c:err:richedit:ReadStyleSheet skipping optional destination
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
0214:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
024c:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
0284:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
02e4:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
0328:err:mscoree:LoadLibraryShim error reading registry key for installroot
mv: cannot move 'allredist/photoshop.png' to '/root/.local/share/icons/photoshop.png': No such file or directory

Can you please let me know what I'm doing wrong and how can I fix it? Thank you!

**Comment by MiMillieuh** [comment]
You're trying to install it with sudo and without specifying a path.

if you want my preferred configuration is to create a folder called `.WineApps` in your home directory and then launch the installer with `sh photoshop2021install.sh /home/yourusername/.WineApps`

And you should be good to go

**Comment by ikim23code** [comment]
I feel embarrassed about this... Thank you very much! It works like a charm now, even the export function works perfect.
