### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by MarkKocherovsky** [LinSoftWin/Photoshop-CC2022-Linux#115]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
eg : CC2021

**Describe the bug**
I'm trying to run the install script and I get the following error: ``allredist/setup_vkd3d_proton.sh: 78: Bad substitution``

**Screenshots**
![image](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/assets/67556945/65260359-d6b7-4d5f-99ac-e4478b9bcfbc)

**System informations**
- Distro : Ubuntu 22.04.3 Jammy
- GPU :  NVIDIA 3060 Mobile
- WINE version : 8.0.2

**Comment by MiMillieuh** [comment]
Do you have :

- I386 architecture enabled ?
- tried wine-devel branch ?
- a vulkan capable driver (nvidia proprietary in your case )?
- cloned or downloaded from releases ?

**Comment by MarkKocherovsky** [comment]
> I386 architecture enabled ?
I have ``i386: /usr/bin/i386 /usr/share/man/man8/i386.8.gz``

> tried wine-devel branch ?
I have wine-devel 8.15~jammy-1 installed but I'm not sure I'm using it

> a vulkan capable driver (nvidia proprietary in your case )?
NVIDIA Server Driver metapackage from nvidia-driver-525-server

> cloned or downloaded from releases ?
I cloned from the latest CC2021 release

Also, does this version of photoshop come cracked? I know it used to but that may have changed.

**Comment by MiMillieuh** [comment]
> > I386 architecture enabled ?
> I have ``i386: /usr/bin/i386 /usr/share/man/man8/i386.8.gz``
> 
> > tried wine-devel branch ?
> I have wine-devel 8.15~jammy-1 installed but I'm not sure I'm using it
> 
> > a vulkan capable driver (nvidia proprietary in your case )?
> NVIDIA Server Driver metapackage from nvidia-driver-525-server
> 
> > cloned or downloaded from releases ?
> I cloned from the latest CC2021 release
> 
> Also, does this version of photoshop come cracked? I know it used to but that may have changed.
> 

Unfortunately it does, the activation process still use an embedded internet explorer. I tried to do my own login system but it would be just like hiding the misery under a carpet... and less trust worthy tho.

**Comment by MarkKocherovsky** [comment]
Somehow it decided to work today. I'll leave this open until I've tested it thoroughly

> Unfortunately it does, the activation process still use an embedded internet explorer. I tried to do my own login system but it would be just like hiding the misery under a carpet... and less trust worthy tho.

Oh no that's fine, as long as I can use it for free I'm not bothered.

**Comment by MiMillieuh** [comment]
Well sometimes it can be.

Keep it open if I have no news I'll close it next week :) 

And by the way the licence thing really bother me cause I literally pay them for nothing... but since I use it in my work I guess I have no choice :(
