### ISSUE TITLE
Cannot open CR3 files

### ISSUE THREAD

**Issue by MarkKocherovsky** [LinSoftWin/Photoshop-CC2022-Linux#116]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
eg : CC2021

**Describe the bug**
I'm trying to open some CR3 raw files from my Canon EOS 50 Mk2, and I get the following error: ``Could not complete your request because it is not the right kind of document.`` I've installed Camera Raw as shown in the instructions, and the plug-in options are available in Preferences. When I try to place it on a file, I get ``Could not place <IMG> because no parser or file format can open the file.``

**To Reproduce**
1. Open Photoshop
2. Try to open image from click-and-dragging or the open menu

**Expected behavior**
Photo should open as normal

**Screenshots**
![image](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/assets/67556945/9b9fb39e-5da8-425c-aaee-b499e340ddbb)
![image](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/assets/67556945/6f87fcb3-1863-4ae2-bf1c-31da18b3ad63)

**System informations**
- Distro : Ubuntu 22.04
- GPU : NVIDIA RTX 3060 Mobile
- WINE version : 8.15

**Comment by MiMillieuh** [comment]
Did you installed photoshop with camera raw ? 

it's the cr script

if not that's the issue

but I also thing that CR3 was introduced in a newer version than the one shipped.


could you try installing photoshop without camera raw and install the latest version of camera raw in standalone ?


https://helpx.adobe.com/ch_fr/camera-raw/kb/camera-raw-plug-in-installer.html

**Comment by MarkKocherovsky** [comment]
I used the standalone as is written in the README.

**Comment by MiMillieuh** [comment]
Yes but can you try to install a more recent version ? like the one I linked ?

**Comment by MarkKocherovsky** [comment]
Alright, 15.5 works! Thank you!
