### ISSUE TITLE
Use Legacy "New Document" Interface is grayed out and ticked/enabled

### ISSUE THREAD

**Issue by Clyde-Timonera** [LinSoftWin/Photoshop-CC2022-Linux#118]
Photoshop version
CC2021

Describe the bug*
Use Legacy "New Document" Interface is grayed out and ticked/enabled

**To Reproduce**
1. Go to Preferences
2. Use Legacy "New Document" is grayed out

Expected behavior
Easily turn off Legacy New Doc interface

**Screenshots**
![image](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/assets/78290310/74c8c6dc-7963-41a2-94fc-fb3be6548049)

**System informations**
- Distro : Ubuntu 22.04 
- GPU : (NVIDIA GTX 1050)
- WINE version : 8.0.2 (Installed Photoshop with 7.0)

**Comment by Clyde-Timonera** [comment]
FIxed by upgrading to 2022 version

**Comment by MiMillieuh** [comment]
It's international because the normal interface can crash 2021.

I would recommend sticking to 2021 as 2022 isn't stable
