### ISSUE TITLE
Camera Raw Filter not working

### ISSUE THREAD

**Issue by rickywid** [LinSoftWin/Photoshop-CC2022-Linux#120]
**PLEASE READ THE REQUIREMENT BEFORE FILLING A BUG. ALSO PLEASE CHECK IF A SIMILLAR ISSUE ISN'T OPEN**

**Photoshop version**
eg : CC2021

**Describe the bug**
Camera Raw Filter is not working after following installation.

```
curl -L "https://download.adobe.com/pub/adobe/photoshop/cameraraw/win/12.x/CameraRaw_12_2_1.exe" > CameraRaw_12_2_1.exe WINEPREFIX=/Path/To/Your/Photoshop/Install/Adobe-Photoshop wine CameraRaw_12_2_1.exe
```

**To Reproduce**
1. Go to 'Edit -> Preferences -> Camera Raw Filter'

**Expected behavior**
Camera Raw Filter Preferences window should open.

**Screenshots**
[screenshot](https://imgur.com/a/ualRhLU)

**System informations**
- Distro : Fedora 38
- GPU : Intel Integrated Graphics
- WINE version : wine-8.19 

**Additional context**
Photoshop application itself works fine.

**Is some information are missing it might take longer to find the issue so please complete carefully**

**Comment by MiMillieuh** [comment]
Hello, 

Can you please try this solution ? 

```
Did you installed photoshop with camera raw ?

it's the cr script

if not that's the issue

but I also thing that CR3 was introduced in a newer version than the one shipped.

could you try installing photoshop without camera raw and install the latest version of camera raw in standalone ?

https://helpx.adobe.com/ch_fr/camera-raw/kb/camera-raw-plug-in-installer.html
```

https://github.com/LinSoftWin/Photoshop-CC2022-Linux/issues/116#issuecomment-1721170120

**Comment by rickywid** [comment]
> Hello,
> 
> Can you please try this solution ?
> 
> ```
> Did you installed photoshop with camera raw ?
> 
> it's the cr script
> 
> if not that's the issue
> 
> but I also thing that CR3 was introduced in a newer version than the one shipped.
> 
> could you try installing photoshop without camera raw and install the latest version of camera raw in standalone ?
> 
> https://helpx.adobe.com/ch_fr/camera-raw/kb/camera-raw-plug-in-installer.html
> ```
> 
> [#116 (comment)](https://github.com/LinSoftWin/Photoshop-CC2022-Linux/issues/116#issuecomment-1721170120)

Ok so I need to reinstall photoshop and then download the latest version of Camera Raw (v16)?

**Comment by MiMillieuh** [comment]
Closed since no further answer.
